algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

num: real

inicio
escreva("Digite um número? ")
leia(num)
    se (num%2=0) entao
        escreval ("O número ",num," é par.")
    senao
        escreval ("O número ",num," é impar.")
fimse

fimalgoritmo