algoritmo "Exercicio15"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

V1: real

inicio

Escreva("Digite um valor: ")
leia(V1)
    se (V1>=0) entao
        escreval ("O valor (",V1,") é positivo")
    senao
        escreval ("O valor (",V1,") é negativo")
    fimse
fimalgoritmo
