algoritmo "Notas"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

N1,N2,N3, M: real

inicio

escreva("Informe a nota 1: ")
Leia(N1)
escreva("Informe a nota 2: ")
Leia(N2)
escreva("Informe a nota 3: ")
Leia(N3)
M<-(N1*2+N2*3+N3*5)/10
escreva("A Média Final desse aluno será de: ",M)

fimalgoritmo