algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

A: real
inicio

escreva("Você tem dinheiro: ")
leia(A)
se (A>10) entao
    escreval ("Deve ir na loja da mariquinha")
senao
    escreval ("fique em casa")
fimse 
fimalgoritmo