algoritmo "Temperatura"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

F, C: real

inicio

escreva("Informe a temperatura em graus Celsius (ºC): ")
leia(C)
F<-(9*C+160)/5
escreva("A temperatura correspondente em graus Fahrenheit (ºF) é de: ",F)

fimalgoritmo