algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

A, B, C: inteiro
inicio

A <- 30
B <-20
C <- A+B
escreval (C)
B <- 10
escreval (B,", ",C)
C <- A+B
escreva (A,", ", B,", ",C)

fimalgoritmo